const LABELS = {
  healthy: "Healthy",
  monitor: "Monitor",
  critical: "Critical",
  pending: "Pending",
  "in-progress": "In progress",
  completed: "Completed",
  escalated: "Escalated",
  skipped: "Skipped",
  "false-positive": "False positive",
  "anomaly-found": "Anomaly found",
  "Pending Review": "Pending Review",
  Reassigned: "Reassigned",
  approved: "Approved",
  deferred: "Deferred",
  rejected: "Rejected",
  active: "Active",
  invalidated: "Invalidated",
  regenerated: "Regenerated",
  inactive: "Inactive",
  locked: "Locked",
  online: "Online",
  degraded: "Degraded",
  offline: "Offline",
  open: "Open",
  investigating: "Investigating",
  resolved: "Resolved",
  info: "Info",
  warning: "Warning",
  error: "Error",
  synced: "Synced",
  failed: "Failed",
  manual: "Manual",
  ai: "AI",
  confirmed: "Confirmed",
  discarded: "Discarded",
};

export default function StatusPill({ status }) {
  return <span className={`status-pill status-${status}`}>{LABELS[status] || status}</span>;
}
